# Convex Optimization
## Tutorial 5
### Tanmay Garg CS20BTECH11063

In [46]:
#Importing required Libraries
import numpy as np
import matplotlib.pyplot as plt
import cvxpy as cp

In [47]:
# We have n factories and m destinations
# S vector will be the supply vector from each factory
# D vector will be the demand vector at each destination
# C will the cost of shipping matrix (n x m)
# Q will quantitiy of each product shipped from each factory to each destination (n x m)

In [48]:
n = 3
m = 5
S = np.matrix('40 50 45')
S = S.T
D = np.matrix('45 20 30 30 10')
D = D.T
C = np.matrix('8 6 10 9 8; 9 12 13 7 5; 14 9 16 5 2')

In [49]:
Q = cp.Variable((n, m))

MyObjective = cp.Minimize(cp.sum(cp.multiply(C, Q)))

MyConstraint = [
    Q >= 0,
    cp.matmul(Q, np.ones((m, 1))) == S,
    cp.matmul(Q.T, np.ones((n, 1))) >= D
]

In [50]:
MyProblem = cp.Problem(MyObjective, MyConstraint)
value = MyProblem.solve()
print(value)

1025.0000000255045


In [51]:
print("The quanity of each product shipped from each factory to each destination")
print(np.round(Q.value))

print("The total cost of shipping each product: ", value)

print("Total quantity supplied from each factory: ", np.sum(Q.value, axis=1))
print("Total quantity received by each destination: ", np.sum(Q.value, axis=0))

The quanity of each product shipped from each factory to each destination
[[ 0. 15. 25.  0.  0.]
 [45.  0.  5.  0.  0.]
 [ 0.  5.  0. 30. 10.]]
The total cost of shipping each product:  1025.0000000255045
Total quantity supplied from each factory:  [40. 50. 45.]
Total quantity received by each destination:  [45. 20. 30. 30. 10.]
